//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using UnityEngine.UI;
using System;

public class DoubleTheCoinPowerUp : IPlayerPowerUp
{
	private PowerUpManager powerUpManager;

	public DoubleTheCoinPowerUp(PowerUpManager powerUpManager){
		this.powerUpManager = powerUpManager;	
	}

	public void executePowerUpRelatedTasks(GameObject powerUpSlider){

		Debug.Log ("Double the coin power up used.");
	}

}


